### ISSUE TITLE
Find Broken Motifs for a combination of SNPs

### ISSUE THREAD

**Issue by YichaoOU** [Simon-Coetzee/motifBreakR#13]
Hi,

Suppose that you have two SNPs that are adjacent, currently, motifBreakR will analyze these two SNPs separately, however, I'm looking for a motif that could be broken by the two SNPs together. Is it possible for motifBreakR to consider a combination of SNPs?

Thanks,
Yichao

**Comment by Simon-Coetzee** [comment]
This work is currently underway, I'll post here when the code is rolled out

**Comment by dennishazelett** [comment]
This can be done with custom variants, e.g.:
```
chr1  12345  12349  chr1:12345:12349:ACTTG:AGTCG
```
