### ISSUE TITLE
Only show "?" when using plotMB

### ISSUE THREAD

**Issue by danliangunc** [Simon-Coetzee/motifBreakR#14]
<img width="725" alt="Screen Shot 2019-06-07 at 12 36 51 PM" src="https://user-images.githubusercontent.com/48070163/59119511-0017da00-8921-11e9-905e-0c41f04a9a2d.png">

When I used plotMB(), it only showed "?". Really confused, nay suggestion?

Thanks!

**Comment by Simon-Coetzee** [comment]
I'm not sure the exact cause of this problem, but some of our dependencies changed, and I'm working on refactoring the plotting code currently. Expect and update soon.
