### ISSUE TITLE
Is  it possible to use custom motif database ?

### ISSUE THREAD

**Issue by gouthamatla** [Simon-Coetzee/motifBreakR#17]
Hi,
I have  custom motifs in transfac format. These are the 'root' motifs after clustering all the PWMs. I would like to use these root motifs for MotifbreakR analysis. Let me know if I will be able to do that. 

Thanks,
Goutham A

**Comment by dennishazelett** [comment]
You will have to format your custom motifs compatible with R/Bioconductor package MotifDb.
