### ISSUE TITLE
Software Redefines What an Indel is

### ISSUE THREAD

**Issue by DarioS** [Simon-Coetzee/motifBreakR#28]
A DNP, such as CC > TT, is considered to be an indel:

```r
is.indel <- ref_len > 1L | alt_len > 1L
```

It appears that the software considers anything that is not a SNP to be an indel. But [DNP](https://docs.gdc.cancer.gov/Encyclopedia/pages/Variant_Type/) or [TNP](https://docs.gdc.cancer.gov/Encyclopedia/pages/Variant_Type/) are not indels and I was confused at first to see:

```r
ref.len <- nchar(fsnplist.indel[nchar(fsnplist.indel$REF) == nchar(fsnplist.indel$ALT)]$REF) # Indel variants same length as reference.
```

 Could a better categorisation of variants be used, such as Simple Nucleotide Variants (SNV) and indels? Typically, the genomics abbreviations are:

> SNP, single-nucleotide polymorphism; SNV, simple nucleotide variant

**Comment by dennishazelett** [comment]
Hi, computationally we treat indels and serial substitutions (or however you want to label them) the same for purposes of calculation.
