### ISSUE TITLE
multiple cores do not seem to be used

### ISSUE THREAD

**Issue by paul-shannon** [Simon-Coetzee/motifBreakR#33]
@scoetzee  @Simon-Coetzee 
First,  thanks for this package.  It has been very helpful.

In scaling up our use to explore eQTLs from Alzheimer's loci, I cannot seem to make good use of the BPPARAM argument.   

With ```MulticoreParam(workers=40)``` on a linux box with 84 cores, watching ```top``` I see multiple R processes appear **very** briefly, and then disappear, leaving only one R process,  running for an additional 10 minutes.  The total execution time seems to be linear.  
I am using 40 rsids at a time, against 80 motifs from MotifDb.

Any suggestions?

**Comment by Simon-Coetzee** [comment]
I had a problem with how I was implementing the parallel code, It should be fixed here (on github) now, and should be propagating to Bioconductor devel soon.

**Comment by paul-shannon** [comment]
Thanks, Simon!

I’m trying it out now.

 - Paul

**Comment by paul-shannon** [comment]
Works great!  Fast!

Thanks, Simon.
