### ISSUE TITLE
SNP at RNA level

### ISSUE THREAD

**Issue by BioEpi** [Simon-Coetzee/motifBreakR#39]
Hello,
    motifbreakR is a great tool to analyze the effect of SNPs on TF binding sites. 
    I want to know whether motifbreakR is able to analyze the roles of SNPs at RNA levels.
Best,

**Comment by Simon-Coetzee** [comment]
Unfortunately only looks for the strength of the disruption on a motif in DNA. Correlating with RNA levels would be a downstream analysis.
