### ISSUE TITLE
Bug in calculatePvalue

### ISSUE THREAD

**Issue by sushilashenoy** [Simon-Coetzee/motifBreakR#4]
I get an error when using the calculatePvalue function.

The error:
`Error in pwmList[[rownames(pwmmeta)]] :`
`attempt to select less than one element`

My script:
`library('BSgenome.Dmelanogaster.UCSC.dm6')`
`library('motifbreakR')`
`library('MotifDb')`
`genome <- BSgenome.Dmelanogaster.UCSC.dm6`
`snps.mb <- snps.from.file('dgrp_test_snps.bed.txt', search.genome=genome, format='bed')`
`motifs <- query(MotifDb, 'dmelanogaster')`
`results <- motifbreakR(snps.mb, pwmList=motifs, filterp=TRUE, threshold=1e-4)`
`results.p <- calculatePvalue(results)`

Input file:
[dgrp_test_snps.bed.txt](https://github.com/Simon-Coetzee/motifBreakR/files/210480/dgrp_test_snps.bed.txt)

When I use the debugging browser the problem appears to be that the `pwmmeta` table (and the `pwmListmeta` table returned by `mcols(attributes(results)$motifs)` does not have row names, so `rownames(pwmmeta)` is `NULL`.

**Comment by sushilashenoy** [comment]
While attempting to fix this I ran into a separate error in the same function when `pwmmeta` has more than 1 row, which could be ignored by replacing `rownames(pwmmeta)` with `rownames(pwmmeta)[1]`. I submitted a pull request with these changes.

**Comment by aprice26** [comment]
I'm also having this issue with the same error. Here's the code I am using:

```
library("motifbreakR")
library(BSgenome)
library(BSgenome.Hsapiens.UCSC.hg19)
library(SNPlocs.Hsapiens.dbSNP142.GRCh37)
library(MotifDb)

# load in SNPs
snps = c(<set of 36 SNPs>)
snps.mb = snps.from.rsid(rsid = snps,
                          dbSNP = SNPlocs.Hsapiens.dbSNP142.GRCh37,
                          search.genome = BSgenome.Hsapiens.UCSC.hg19)
# find broken motifs
data(motifbreakR_motif)
resultsLOG = motifbreakR(snpList = snps.mb, filterp = TRUE,
                       pwmList = motifbreakR_motif,
                       threshold = .10,
                       method = "log",
                       bkg = c(A=0.25, C=0.25, G=0.25, T=0.25))
resultsLOG = calculatePvalue(resultsLOG)
Error in pwmList[[rownames(pwmmeta)]] : 
  attempt to select less than one element in get1index
```

**Comment by YiweiNiu** [comment]
I'm also having this issue with the same error.  Do you know how to fix it?

**Comment by sushilashenoy** [comment]
Been a while but I think if you assign names to the pwmList argument it should work.

**Comment by YiweiNiu** [comment]
Could you please be more specific? I don't know how to assign names to the pwmList.

**Comment by sushilashenoy** [comment]
names(motif_list) <- 1:length(motif_list)

Substitute motif_list with whatever you are passing to motifbreakR as pwmList.

**Comment by YiweiNiu** [comment]
Thank you for your quick reply! But I still got the error by doing this.

**Comment by bapoorva** [comment]
This issue has been fixed. If you still have trouble, install motifbreakR from github using

install.packages("devtools")
devtools::install_github("Simon-Coetzee/motifBreakR")

and restart your R session
