### ISSUE TITLE
motifbreakR error when set show.neutral = TRUE

### ISSUE THREAD

**Issue by hdm2020** [Simon-Coetzee/motifBreakR#43]
when I set show.neutral = TRUE, there is an error as follows:
![image](https://user-images.githubusercontent.com/71557587/180985166-9198edbc-6146-438c-9dd6-27a3a53300ef.png)
and if show.neutral = FALSE, it is okay to finish the procedure.
![image](https://user-images.githubusercontent.com/71557587/180985830-73258629-6c38-4bfb-9723-c5ecdf6325b5.png)
so,Does anyone know why this error occurred? I will appreciate it for your answers.

**Comment by Simon-Coetzee** [comment]
Hi, sorry you're having trouble - can you please share the five variants you're testing with?

**Comment by hdm2020** [comment]
Hi, thanks for your reply, the 5 variants I used are as follows:
![image](https://user-images.githubusercontent.com/71557587/181185374-e894d4d7-7cc2-45d2-84d9-bde94c85d147.png)

**Comment by Simon-Coetzee** [comment]
I think this bug got fixed in the most recent update here on github, should be going out to bioc soon.
