### ISSUE TITLE
motifbreakR() never returns a result

### ISSUE THREAD

**Issue by 5Aki1** [Simon-Coetzee/motifBreakR#44]
Hi! I am not sure if there is a bug somewhere, but I can't seem to get motifbreakR() to return anything except for "Warning: No SNP/Motif Interactions reached threshold". This includes the practical example found in the documentation

![image](https://user-images.githubusercontent.com/9410824/191361397-eafe530a-e694-4984-83f3-96299344603d.png)

**Comment by ashvinravi** [comment]
Hi! I am getting the issue when I run the vignette/documentation - were you able to fix this? I used both dbSNP package 142 and 144 but still do not see any SNP/Motif interactions that reach the threshold.

**Comment by Simon-Coetzee** [comment]
I believe I have tracked down some code where all changes were being called neutral when using motifbreakr with score based thresholding, rather than p-value thresholding. It has been fixed here on github and should be making it's way out to bioc shortly.

**Comment by ashvinravi** [comment]
It actually started to work for me now - when I use variants[1:n], where n=range of SNPs, I get results so it may be something with the snpList formatting as well. Thank you for getting back to me regardless!
