### ISSUE TITLE
plotMB error: Error in if (doRev) { : the condition has length > 1

### ISSUE THREAD

**Issue by jing-wan** [Simon-Coetzee/motifBreakR#46]
Hi,
I got this error when I use plotMB:
```
plotMB(my.results, "rs2275915", effect = "strong")
Error in if (doRev) { : the condition has length > 1
```

Also error for the example:
```
data(example.results)
example.results
plotMB(example.results, "rs2661839", effect = "strong")
Error in if ((mcols(mresult)$varType == "Insertion" & mcols(mresult)$alleleDiff <  :  argument is of length zero

```

my.results is generated by motifbreakR, and looks like the same as  example.results. 
The version is motifbreakR 2.12.2
Thanks.

**Comment by Simon-Coetzee** [comment]
is it possible that you have a palindromic motif with hits on both the + and - strands in your results, with the same providerID and providerName? I'm trying to narrow down the problem. If you could attach your results here it would be easier.

**Comment by szhang1112** [comment]
I also got this error when visualizing the motifs - any solution yet?

**Comment by bioarpit1** [comment]
same error any solution ?

**Comment by dennishazelett** [comment]
this issue has been resolved on another thread, please see https://github.com/Simon-Coetzee/motifBreakR/issues/53#issuecomment-2135865036
