### ISSUE TITLE
Error in run motifbreakR

### ISSUE THREAD

**Issue by tzhu-bio** [Simon-Coetzee/motifBreakR#51]
Thanks for your motifbreakR.

I'm trying to run your sample code, but I'm encountering errors in parallel.

![image](https://user-images.githubusercontent.com/54537420/226093696-14511764-01f0-413c-b6f0-df22aa23f821.png)

Can you give me some help? Thanks

![image](https://user-images.githubusercontent.com/54537420/226093808-a9164159-0e6c-4bab-8a84-cbe8ecde2740.png)

**Comment by Simon-Coetzee** [comment]
I'm not sure what the nature of your error is, you can try running it with SerialParam() and maybe get a better error message. However the first thing I would suggest is to try the most updated version of motifbreakr on bioconductor - 2.12.3. or from here on GitHub which is 2.13.7
