### ISSUE TITLE
Strand information

### ISSUE THREAD

**Issue by xtmgah** [Simon-Coetzee/motifBreakR#6]
Hello:

I am running the motifBreakR and want to find the promoter mutation effect on transcription factor binding sites. i make two same bed file but with different strand ( "+" and "-").  The result are different. So, what the "Strand" means in the provided bed file? All the mutation i generated is on the reference strand (like in vcf files). So, which strand should i use? Thanks.

**Comment by dennishazelett** [comment]
If you change the strand you change the meaning of the bed file completely. For example if you indicate in your SNP label that the values are ":T:G", motifbreakR understands by default that there is a "T" in the reference genome at that position, and it should substitute a "G" to calculate SNP effects. BUT if you put "-" in the strand field of the bed file, motifbreakR will reverse complement the SNP to make it compatible with the reference genome. I recommend sticking to the + strand to avoid confusion. Does this answer your question?

**Comment by xtmgah** [comment]
Yes. Great. Thanks for your explanation.

**Comment by xtmgah** [comment]
Another question, Do you know which program or software can be used to extract the Motifs that cover at specific genome location, and also show the core motif information (for example, ETS as "TTCC") ? 

Thanks.

**Comment by dennishazelett** [comment]
use MotifDb package; see [query function](http://127.0.0.1:11615/library/MotifDb/html/query.html)
