### ISSUE TITLE
Loading VCF using snps.from.file()

### ISSUE THREAD

**Issue by ATpoint** [Simon-Coetzee/motifBreakR#8]
Hi,

I have a problem using the function snps.from.file on a vcf file (motifbreakR V.1.4.0).

1) First of all, library(motifbreakR) misses to load the VariantAnnotation library, hence the readVFC function within snps.from.file()  is undefined.

2) in line 10 of snps.from.file, snps <- snps[elementLengths(info(snps).....
elementLengths() is not functional in the current BSgenome, and should be replaced by elementNROWS(). B
Both 1) and 2) are simple to solve.

3) This is the actual point of this issue: snps.from.file() in line 10 and 12 searches for "VT" in the info(snps). What actually is "VT". I could not find it in the VCF documentation, and my vcf (created by VarDict) does not contain any "VT" in the INFO column. 
In the meantime, I will convert my vcf to bed, as suggested in the manual, but starting directly from vcf would be desirable. Can you help me here?

best wishes,
Alexander

**Comment by lixin4306ren** [comment]
I got same issue, doesn't work for vcf file. No "VT" field for lots of vcf source.
